#! /bin/bash



echo "Loading functions of user creation script"
	add-single (){
	if [[ $EUID -eq 0 ]]
	then
        	read -p "Enter a Username to be created: " uservar 
		useradd -g org -m -r -s /bin/bash -p 'password' $uservar
		echo $uservar >> usernames.txt
		echo "User Created"		
	else
               echo "userscript must be run as root"
	fi

	}

	remove-single (){
		read -p "Enter a existing Username to be removed: " rmuser
		userdel  $rmuser
		echo "User Delted"
	}

	add-bulk (){
		read -e -p "Enter a file with Usernames to be created: " bulkinput

			for name in $(cat $bulkinput); do
	       			useradd -g org -m -r -s /bin/bash -p 'password' $name
      				echo $name >> bulkuser.txt
				echo "Users Created"
			done 	
	}

	remove-bulk () {
		read -e -p "Enter a file with Usernames to be removed: " brinput
			for names in $(cat $brinput); do 
				userdel  $names
				echo "Users Delted"
			done
	}

add-single	
remove-single	
add-bulk	
remove-bulk
